name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [${{ steps.nvm.outputs.NVMRC }}]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Read .nvmrc
      uses: actions/github-script@v5
      id: nvm
      with:
        script: |
          return fs.readFileSync('.nvmrc', 'utf8').trim()

    - name: Setup Node.js version
      uses: actions/setup-node@v2
      with:
        node-version: ${{ steps.nvm.outputs.NVMRC }}

    - name: Cache .pnpm-store
      uses: actions/cache@v3
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}

    - name: Install pnpm
      run: npm install -g pnpm@8.6.7

    - name: Install dependencies
      run: pnpm install

    - name: Test with coverage
      run: pnpm run test:coverage
